const domains_k = {
	"KY_K_CC": {
		"id": "KY_K_CC",
		"grade": "KY.K",
		"ordinal": "CC",
		"name": "Counting and Cardinality",
		"ordering": "1"
	},
	"KY_K_OA": {
		"id": "KY_K_OA",
		"grade": "KY.K",
		"ordinal": "OA",
		"name": "Operations and Algebraic Thinking",
		"ordering": "2"
	},
	"KY_K_NBT": {
		"id": "KY_K_NBT",
		"grade": "KY.K",
		"ordinal": "NBT",
		"name": "Number and Operations in Base Ten",
		"ordering": "3"
	},
	"KY_K_MD": {
		"id": "KY_K_MD",
		"grade": "KY.K",
		"ordinal": "MD",
		"name": "Measurement and Data",
		"ordering": "4"
	},
	"KY_K_G": {
		"id": "KY_K_G",
		"grade": "KY.K",
		"ordinal": "G",
		"name": "Geometry",
		"ordering": "5"
	}
};

const clusters_k = {
	"KY_K_CCa": {
		"id": "KY_K_CCa",
		"ccmathdomain_id": "KY_K_CC",
		"ordinal": "1",
		"name": "Know number names and the count sequence.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_CCb": {
		"id": "KY_K_CCb",
		"ccmathdomain_id": "KY_K_CC",
		"ordinal": "2",
		"name": "Count to tell the number of objects.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_CCc": {
		"id": "KY_K_CCc",
		"ccmathdomain_id": "KY_K_CC",
		"ordinal": "3",
		"name": "Compare numbers.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_OAa": {
		"id": "KY_K_OAa",
		"ccmathdomain_id": "KY_K_OA",
		"ordinal": "1",
		"name": "Understand addition as putting together and adding to, and understand subtraction as taking apart and taking from.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_NBTa": {
		"id": "KY_K_NBTa",
		"ccmathdomain_id": "KY_K_NBT",
		"ordinal": "1",
		"name": "Working with numbers 11-19 to gain foundations for place value.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_MDa": {
		"id": "KY_K_MDa",
		"ccmathdomain_id": "KY_K_MD",
		"ordinal": "1",
		"name": "Describe and compare measurable attributes.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_MDb": {
		"id": "KY_K_MDb",
		"ccmathdomain_id": "KY_K_MD",
		"ordinal": "2",
		"name": "Classify objects and count the number of objects in each category.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_MDc": {
		"id": "KY_K_MDc",
		"ccmathdomain_id": "KY_K_MD",
		"ordinal": "3",
		"name": "Identify coins by name.",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_Ga": {
		"id": "KY_K_Ga",
		"ccmathdomain_id": "KY_K_G",
		"ordinal": "1",
		"name": "Identify and describe shapes (squares, circles, triangles, rectangles, hexagons, cubes, cones, cylinders and spheres).",
		"msa": "0",
		"wap": "0"
	},
	"KY_K_Gb": {
		"id": "KY_K_Gb",
		"ccmathdomain_id": "KY_K_G",
		"ordinal": "1",
		"name": "Analyze, compare, create and compose shapes.",
		"msa": "0",
		"wap": "0"
	}
};

const standards_k = {
	"KY_K_CC_1": {
		"id": "KY_K_CC_1",
		"ccmathcluster_id": "KY_K_CCa",
		"ordinal": "1",
		"desc": "<p>Count<\/p>\r\n<p>a. Count to 100 by ones and by tens.<\/p>\r\n<p>b. Count backwards from 30 by ones.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_CC_2": {
		"id": "KY_K_CC_2",
		"ccmathcluster_id": "KY_K_CCa",
		"ordinal": "2",
		"desc": "<p>Count forward beginning from a given number within the known sequence within 100 (instead of having to begin at 1).<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_CC_3": {
		"id": "KY_K_CC_3",
		"ccmathcluster_id": "KY_K_CCa",
		"ordinal": "3",
		"desc": "<p>Represent numbers.<\/p>>\r\n<p>a. Write numbers from 0 to 20.<\/p>>\r\n<p>b. Represent a number of objects with a written numeral 0-20 (with 0 representing a count of no objects).<\/p>>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_CC_4": {
		"id": "KY_K_CC_4",
		"ccmathcluster_id": "KY_K_CCb",
		"ordinal": "4",
		"desc": "<p>Understand the relationship between numbers and quantities; connect counting to cardinality.<\/p>\r\n<p>a. When counting objects, say the number names in the standard order, pairing each object with one and only one number name and each number name with one and only one object.<\/p>\r\n<p>b. Understand that the last number name said tells the number of objects counted. The number of objects is the same regardless of their arrangement or the order in which they were counted.<\/p>\r\n<p>c. Understand that each successive number name refers to a quantity that is one larger.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_CC_5": {
		"id": "KY_K_CC_5",
		"ccmathcluster_id": "KY_K_CCb",
		"ordinal": "5",
		"desc": "<p>Given a number from 1-20, count out that many objects.<\/p>\r\n<p>a. Count to answer “how many?” questions with as many as 20 things arranged in a line, a rectangular array, or a circle.<\/p>\r\n<p>b. Count to answer “how many?” questions with as many as 10 things in a scattered configuration.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_CC_6": {
		"id": "KY_K_CC_6",
		"ccmathcluster_id": "KY_K_CCc",
		"ordinal": "6",
		"desc": "<p>Identiy whether the number of objects in one group is greater than, less than, or equal to the number of objects in another group.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_CC_7": {
		"id": "KY_K_CC_7",
		"ccmathcluster_id": "KY_K_CCc",
		"ordinal": "6",
		"desc": "<p>Compare two numbers between 1 and 10 presented as written numerals.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_OA_1": {
		"id": "KY_K_OA_1",
		"ccmathcluster_id": "KY_K_OAa",
		"ordinal": "1",
		"desc": "<p>Represent addition and subtraction with objects, fingers, mental images, drawings, sounds, acting out situations, verbal explanations, expressions, or equations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_OA_2": {
		"id": "KY_K_OA_2",
		"ccmathcluster_id": "KY_K_OAa",
		"ordinal": "2",
		"desc": "<p>Solve addition and subtraction word problems and add and subtract within 10 by using objects or drawings to represent the problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_OA_3": {
		"id": "KY_K_OA_3",
		"ccmathcluster_id": "KY_K_OAa",
		"ordinal": "3",
		"desc": "<p>Decompose numbers less than or equal to 10.<\/p>\r\n<p>a. Decompose numbers into two groups in more than one way by using objects or drawings and record each decomposition by a drawing or equation.<\/p>\r\n<p>b. Use objects or drawings to demonstrate equality as the balancing of quantities.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_OA_4": {
		"id": "KY_K_OA_4",
		"ccmathcluster_id": "KY_K_OAa",
		"ordinal": "4",
		"desc": "<p>For any number from 1 to 9, find the number that makes 10 when added to the given number by using objects or drawings and record the answer with a drawing or equation.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_OA_5": {
		"id": "KY_K_OA_5",
		"ccmathcluster_id": "KY_K_OAa",
		"ordinal": "5",
		"desc": "<p>Fluently add and subtract within 5.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_NBT_1": {
		"id": "KY_K_NBT_1",
		"ccmathcluster_id": "KY_K_NBTa",
		"ordinal": "1",
		"desc": "<p>Compose and decompose numbers from 11 to 19 using quantities (numbers with units) of ten ones and some further ones. Understand that these numbers are composed of ten ones and one, two, three, four, five, six, seven, eight, or nine ones.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_MD_1": {
		"id": "KY_K_MD_1",
		"ccmathcluster_id": "KY_K_MDa",
		"ordinal": "1",
		"desc": "<p>Describe measurable attributes (length, height, weight, width, depth) of an object or a set of objects using appropriate vocabulary.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_MD_2": {
		"id": "KY_K_MD_2",
		"ccmathcluster_id": "KY_K_MDa",
		"ordinal": "2",
		"desc": "<p>Directly compare two objects with a measurable attribute in common, to see which object has “more of”/ “less of” the attribute and describe the difference.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_MD_3": {
		"id": "KY_K_MD_3",
		"ccmathcluster_id": "KY_K_MDb",
		"ordinal": "3",
		"desc": "<p>Classify and sort objects or people by attributes. Limit objects or people in each category to be less than or equal to 10.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_MD_4": {
		"id": "KY_K_MD_4",
		"ccmathcluster_id": "KY_K_MDc",
		"ordinal": "4",
		"desc": "<p>Recognize and identify coins by name (penny, nickel, dime, quarter).<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_G_1": {
		"id": "KY_K_G_1",
		"ccmathcluster_id": "KY_K_Ga",
		"ordinal": "1",
		"desc": "<p>Name and describe shapes in the environment.<\/p>\r\n<p>a. Describe objects in the environment using names of shapes.<\/p>\r\n<p>b. Describe the relative positions of these objects using terms above, below, in front of, behind and next to.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_G_2": {
		"id": "KY_K_G_2",
		"ccmathcluster_id": "KY_K_Ga",
		"ordinal": "2",
		"desc": "<p>Correctly name shapes regardless of orientations or overall size.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_G_3": {
		"id": "KY_K_G_3",
		"ccmathcluster_id": "KY_K_Ga",
		"ordinal": "3",
		"desc": "<p>Identify shapes as two-dimensional or three-dimensional.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_G_4": {
		"id": "KY_K_G_4",
		"ccmathcluster_id": "KY_K_Gb",
		"ordinal": "4",
		"desc": "<p>Describe the similarities, differences and attributes of two and three dimensional shapes using different sizes and orientations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_G_5": {
		"id": "KY_K_G_5",
		"ccmathcluster_id": "KY_K_Gb",
		"ordinal": "5",
		"desc": "<p>Model shapes in the world by building figures from components and drawing shapes.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_K_G_6": {
		"id": "KY_K_G_6",
		"ccmathcluster_id": "KY_K_Gb",
		"ordinal": "6",
		"desc": "<p>Compose simple shapes to form larger shapes.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	}
}

const domains_1 = {
	"KY_1_OA": {
		"id": "KY_1_OA",
		"grade": "KY.1",
		"ordinal": "OA",
		"name": "Operations and Algebraic Thinking",
		"ordering": "1"
	},
	"KY_1_NBT": {
		"id": "KY_1_NBT",
		"grade": "KY.1",
		"ordinal": "NBT",
		"name": "Numbers and Operations in Base Ten",
		"ordering": "2"
	},
	"KY_1_MD": {
		"id": "KY_1_MD",
		"grade": "KY.1",
		"ordinal": "MD",
		"name": "Measurement and Data",
		"ordering": "3"
	},
	"KY_1_G": {
		"id": "KY_1_G",
		"grade": "KY.1",
		"ordinal": "G",
		"name": "Geometry",
		"ordering": "4"
	}
};

const clusters_1 = {
	"KY_1_OA_a": {
		"id": "KY_1_OA_a",
		"ccmathdomain_id": "KY_1_OA",
		"name": "Represent and solve problems involving addition and subtraction.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_OA_b": {
		"id": "KY_1_OA_b",
		"ccmathdomain_id": "KY_1_OA",
		"name": "Understand an apply properties of operations and the relationship between addition and subtraction.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_OA_c": {
		"id": "KY_1_OA_c",
		"ccmathdomain_id": "KY_1_OA",
		"name": "Add and subtract within 20.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_OA_d": {
		"id": "KY_1_OA_d",
		"ccmathdomain_id": "KY_1_OA",
		"name": "Work with addition and subtraction equations.",
		"ordinal": "4",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_NBT_a": {
		"id": "KY_1_NBT_a",
		"ccmathdomain_id": "KY_1_NBT",
		"name": "Extend the counting sequence.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_NBT_b": {
		"id": "KY_1_NBT_b",
		"ccmathdomain_id": "KY_1_NBT",
		"name": "Understand place value.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_NBT_c": {
		"id": "KY_1_NBT_c",
		"ccmathdomain_id": "KY_1_NBT",
		"name": "Use place value understanding and properties of operations to add and subtract.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_MD_a": {
		"id": "KY_1_MD_a",
		"ccmathdomain_id": "KY_1_MD",
		"name": "Measure lengths indirectly and by iterating length in units.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_MD_b": {
		"id": "KY_1_MD_b",
		"ccmathdomain_id": "KY_1_MD",
		"name": "Work with time and money.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_MD_c": {
		"id": "KY_1_MD_c",
		"ccmathdomain_id": "KY_1_MD",
		"name": "Understand and apply the statistics process.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_1_G_a": {
		"id": "KY_1_G_a",
		"ccmathdomain_id": "KY_1_G",
		"name": "Reason with shapes and their attributes.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	}
};

const standards_1 = {
	"KY_1_OA_1": {
		"id": "KY_1_OA_1",
		"ccmathcluster_id": "KY_1_OA_a",
		"ordinal": "1",
		"desc": "<p>Use addition and subtraction within 20 to solve word problems involving situations of adding to, taking from, putting together, taking apart and comparing, with unknowns in all positions.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_2": {
		"id": "KY_1_OA_2",
		"ccmathcluster_id": "KY_1_OA_a",
		"ordinal": "2",
		"desc": "<p>Solve word problems that call for addition of three whole numbers whose sum is less than or equal to 20, by using objects, drawings and equations with a symbol for one unknown number to represent the problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_3": {
		"id": "KY_1_OA_3",
		"ccmathcluster_id": "KY_1_OA_b",
		"ordinal": "3",
		"desc": "<p>Apply properties of operations as strategies to add and subtract.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_4": {
		"id": "KY_1_OA_4",
		"ccmathcluster_id": "KY_1_OA_b",
		"ordinal": "4",
		"desc": "<p>Understand subtraction as an unknown-addend problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_5": {
		"id": "KY_1_OA_5",
		"ccmathcluster_id": "KY_1_OA_c",
		"ordinal": "5",
		"desc": "<p>Relate counting to addition and subtraction.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_6": {
		"id": "KY_1_OA_6",
		"ccmathcluster_id": "KY_1_OA_c",
		"ordinal": "6",
		"desc": "<p>Add and subtract within 20.<\/p>\r\n<p>a. Fluently add and subtract within 10.<\/p>\r\n<p>b. Add and subtract within 20, demonstrating fluency for addition and subtraction within 10. Use strategies such as counting on; making 10; decomposing a number leading to a 10; using the relationship between addition and subtraction; creating equivalent but easier or known sums.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_7": {
		"id": "KY_1_OA_7",
		"ccmathcluster_id": "KY_1_OA_d",
		"ordinal": "7",
		"desc": "<p>Understand the meaning of the equal sign and determine if equations involving addition and subtraction are true or false.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_OA_8": {
		"id": "KY_1_OA_8",
		"ccmathcluster_id": "KY_1_OA_d",
		"ordinal": "8",
		"desc": "<p>Determine the unknown whole number in an addition or subtraction equation relating three whole numbers.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_NBT_1": {
		"id": "KY_1_NBT_1",
		"ccmathcluster_id": "KY_1_NBT_a",
		"ordinal": "1",
		"desc": "<p>Count and represent numbers.<\/p>\r\n<p>a. Count forward to and backward from 120, starting at any number less than 120.<\/p>\r\n<p>b. In this range, read and write numerals and represent a number of objects with a written numeral.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_NBT_2": {
		"id": "KY_1_NBT_2",
		"ccmathcluster_id": "KY_1_NBT_b",
		"ordinal": "2",
		"desc": "<p>Understand the two-digits of a two-digit number represent amounts of tens and ones. Understand the following as special cases:<\/p>\r\n<p>a. 10 can be thought of as a bundle of ten ones — called a “ten.”<\/p>\r\n<p>b. The numbers from 11 to 19 are composed of a ten and one, two, three, four, five, six, seven, eight or nine ones.<\/p>\r\n<p>c. The numbers 10, 20, 30, 40, 50, 60, 70, 80, 90 refer to one, two, three, four, five, six, seven, eight or nine tens (and 0 ones).<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_NBT_3": {
		"id": "KY_1_NBT_3",
		"ccmathcluster_id": "KY_1_NBT_b",
		"ordinal": "3",
		"desc": "<p>Compare two two-digit numbers based on meanings of the tens and ones digits, recording the results of comparisons with the symbols >, =, and <.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_NBT_4": {
		"id": "KY_1_NBT_4",
		"ccmathcluster_id": "KY_1_NBT_c",
		"ordinal": "4",
		"desc": "<p>Add within 100 including adding a two-digit number and a one-digit number. Add a two-digit number and a multiple of 10.<\/p>\r\n<p>a. Add within 100 using…<br>• concrete models or drawings;<br>• strategies based on place value;<br>• properties of operations;<br>• the relationship between addition and subtraction.<\/p>\r\n<p>b. Relate the addition strategy to a written method and explain the reasoning used. Understand that in adding two-digit numbers, one adds tens and tens, ones and ones; and sometimes it is necessary to compose a ten.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_NBT_5": {
		"id": "KY_1_NBT_5",
		"ccmathcluster_id": "KY_1_NBT_c",
		"ordinal": "5",
		"desc": "<p>Given a two-digit number, mentally find 10 more or 10 less than the number, without having to count; explain the reasoning used.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_NBT_6": {
		"id": "KY_1_NBT_6",
		"ccmathcluster_id": "KY_1_NBT_c",
		"ordinal": "6",
		"desc": "<p>Subtract multiples of 10 in the range 10-90 from multiples of 10 in the range 10-90 (positive or zero differences).<\/p>\r\n<p>a. Subtract using:<br>• concrete models or drawings;<br>• strategies based on place value;<br>• properties of operations;<br>• the relationship between addition and subtraction<\/p>\r\n<p>b. Relate the subtraction strategy to a written method and explain the reasoning used.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_MD_1": {
		"id": "KY_1_MD_1",
		"ccmathcluster_id": "KY_1_MD_a",
		"ordinal": "1",
		"desc": "<p>Order three objects by length; compare the lengths of two objects indirectly by using a third object.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_MD_2": {
		"id": "KY_1_MD_2",
		"ccmathcluster_id": "KY_1_MD_a",
		"ordinal": "2",
		"desc": "<p>Express the length of an object as a whole number of samesize length units, by laying multiple copies of a shorter object (the length unit) end to end with no gaps or overlaps.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_MD_3": {
		"id": "KY_1_MD_3",
		"ccmathcluster_id": "KY_1_MD_b",
		"ordinal": "3",
		"desc": "<p>Assign values to time and money.<\/p>\r\n<p>a. Tell and write time in hours and half-hours using analog and digital clocks.<\/p>\r\n<p>b. Identify the coins by values (penny, nickel, dime, quarter).<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_MD_4": {
		"id": "KY_1_MD_4",
		"ccmathcluster_id": "KY_1_MD_c",
		"ordinal": "4",
		"desc": "<p>Investigate questions involving categorical data.<\/p>\r\n<p>a. Pose a question that can be answered by gathering data.<\/p>\r\n<p>b. Determine strategy for gathering data from peers.<\/p>\r\n<p>c. Organize and represent data in a table/chart with up to three categories.<\/p>\r\n<p>d. Interpret data to answer questions about the table/chart that connects to the question posed, including total number of data points, how many in each category and how many more or less are in one category than in another.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_G_1": {
		"id": "KY_1_G_1",
		"ccmathcluster_id": "KY_1_G_a",
		"ordinal": "1",
		"desc": "<p>Distinguish between defining attributes versus non-defining attributes; build and draw shapes to possess defining attributes.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_G_2": {
		"id": "KY_1_G_2",
		"ccmathcluster_id": "KY_1_G_a",
		"ordinal": "2",
		"desc": "<p>Compose shapes.<\/p>\r\n<p>a. Compose two-dimensional shapes to create rectangles, squares, trapezoids, triangles, half-circles and quarter-circles composite shape and compose new shapes from the composite shapes.<\/p>\r\n<p>b. Use three-dimensional shapes (cubes, right rectangular prisms, right circular cones and right circular cylinders) to create a composite shape and compose new shapes from the composite shapes<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_1_G_3": {
		"id": "KY_1_G_3",
		"ccmathcluster_id": "KY_1_G_a",
		"ordinal": "3",
		"desc": "<p>Partition circles and rectangles into two and four equal shares, describe the shares using the words halves, fourths and quarters, and use the phrases half of, fourth of and quarter of. Describe the whole as two of or four of the shares. Understand for these examples that decomposing into more equal shares creates smaller shares.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	}
};

const domains_2 = {
	"KY_2_OA": {
		"id": "KY_2_OA",
		"grade": "KY.2",
		"ordinal": "OA",
		"name": "Operations and Algebraic Thinking",
		"ordering": "1"
	},
	"KY_2_NBT": {
		"id": "KY_2_NBT",
		"grade": "KY.2",
		"ordinal": "NBT",
		"name": "Numbers and Operations in Base Ten",
		"ordering": "2"
	},
	"KY_2_MD": {
		"id": "KY_2_MD",
		"grade": "KY.2",
		"ordinal": "MD",
		"name": "Measurement and Data",
		"ordering": "3"
	},
	"KY_2_G": {
		"id": "KY_2_G",
		"grade": "KY.2",
		"ordinal": "G",
		"name": "Geometry",
		"ordering": "4"
	}
};

const clusters_2 = {
	"KY_2_OA_a": {
		"id": "KY_2_OA_a",
		"ccmathdomain_id": "KY_2_OA",
		"name": "Represent and solve problems involving addition and subtraction.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_OA_b": {
		"id": "KY_2_OA_b",
		"ccmathdomain_id": "KY_2_OA",
		"name": "Add and subtract within 20",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_OA_c": {
		"id": "KY_2_OA_c",
		"ccmathdomain_id": "KY_2_OA",
		"name": "Work with equal groups of objects to gain foundations for multiplication.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_NBT_a": {
		"id": "KY_2_NBT_a",
		"ccmathdomain_id": "KY_2_NBT",
		"name": "Understand place value.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_NBT_b": {
		"id": "KY_2_NBT_b",
		"ccmathdomain_id": "KY_2_NBT",
		"name": "Use place value understanding and properties of operations to add and subtract.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_MD_a": {
		"id": "KY_2_MD_a",
		"ccmathdomain_id": "KY_2_MD",
		"name": "Measure and estimate lengths in standard units.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_MD_b": {
		"id": "KY_2_MD_b",
		"ccmathdomain_id": "KY_2_MD",
		"name": "Relate addition and subtraction to length.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_MD_c": {
		"id": "KY_2_MD_c",
		"ccmathdomain_id": "KY_2_MD",
		"name": "Work with time and money.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_MD_d": {
		"id": "KY_2_MD_d",
		"ccmathdomain_id": "KY_2_MD",
		"name": "Understand and apply the statistics process.",
		"ordinal": "4",
		"msa": "0",
		"wap": "0"
	},
	"KY_2_G_a": {
		"id": "KY_2_G_a",
		"ccmathdomain_id": "KY_2_G",
		"name": "Reason with shapes and their attributes.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	}
};

const standards_2 = {
	"KY_2_OA_1": {
		"id": "KY_2_OA_1",
		"ccmathcluster_id": "KY_2_OA_a",
		"ordinal": "1",
		"desc": "<p>Use addition and subtraction within 100 to solve one- and two-step word problems involving situations of adding to, taking from, putting together, taking apart and comparing, with unknowns in all positions, by using drawings and equations with a symbol for the unknown number to represent the problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_OA_2": {
		"id": "KY_2_OA_2",
		"ccmathcluster_id": "KY_2_OA_b",
		"ordinal": "2",
		"desc": "<p>Fluently add and subtract within 20 using mental strategies.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_OA_3": {
		"id": "KY_2_OA_3",
		"ccmathcluster_id": "KY_2_OA_c",
		"ordinal": "3",
		"desc": "<p>Determine whether a group of objects (up to 20) has an odd or even number of members; write an equation to express an even number as a sum of two equal addends.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_OA_4": {
		"id": "KY_2_OA_4",
		"ccmathcluster_id": "KY_2_OA_c",
		"ordinal": "4",
		"desc": "<p>Use addition to find the total number of objects arranged in rectangular arrays with up to 5 rows and up to 5 columns; write an equation to express the total as a sum of equal addends.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_1": {
		"id": "KY_2_NBT_1",
		"ccmathcluster_id": "KY_2_NBT_a",
		"ordinal": "1",
		"desc": "<p>Understand that the three digits of a three-digit number represent amounts of hundreds, tens and ones.<\/p>\r\n<p>Understand the following as special cases:<\/p>\r\n<p>a. 100 can be thought of as a bundle of ten tens — called a “hundred.”<\/p>\r\n<p>b. The numbers 100, 200, 300, 400, 500, 600, 700, 800, 900 refer to one, two, three, four, five, six, seven, eight, or nine hundreds (and 0 tens and 0 ones).<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_2": {
		"id": "KY_2_NBT_2",
		"ccmathcluster_id": "KY_2_NBT_a",
		"ordinal": "2",
		"desc": "<p>Count forwards and backwards within 1000; skip-count by 5s, 10s and 100s.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_3": {
		"id": "KY_2_NBT_3",
		"ccmathcluster_id": "KY_2_NBT_a",
		"ordinal": "3",
		"desc": "<p>Read and write numbers to 1000 using base-ten numerals, number names and expanded form.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_4": {
		"id": "KY_2_NBT_4",
		"ccmathcluster_id": "KY_2_NBT_a",
		"ordinal": "4",
		"desc": "<p>Compare two three-digit numbers based on meanings of the hundreds, tens and ones digits, using >, =, and < symbols to record the results of comparisons.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_5": {
		"id": "KY_2_NBT_5",
		"ccmathcluster_id": "KY_2_NBT_b",
		"ordinal": "5",
		"desc": "<p>Fluently add and subtract within 100 using strategies based on place value, properties of operations and/or the relationship between addition and subtraction.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_6": {
		"id": "KY_2_NBT_6",
		"ccmathcluster_id": "KY_2_NBT_b",
		"ordinal": "6",
		"desc": "<p>Add up to four two-digit numbers using strategies based on place value and properties of operations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_7": {
		"id": "KY_2_NBT_7",
		"ccmathcluster_id": "KY_2_NBT_b",
		"ordinal": "7",
		"desc": "<p>Add and subtract within 1000.<\/p>\r\n<p>a. Represent and solve addition and subtraction problems using…<br>• concrete models or drawings;<br>• strategies based on place value;<br>• properties of operations;<br>• the relationship between addition and subtraction and;<br>• relate drawings and strategies to expressions or equations.<\/p>\r\n<p>b. Understand that in adding or subtracting three-digit numbers, one adds or subtracts hundreds and hundreds, tens and tens, ones and ones; and sometimes it is necessary to compose or decompose tens or hundreds.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_8": {
		"id": "KY_2_NBT_8",
		"ccmathcluster_id": "KY_2_NBT_b",
		"ordinal": "8",
		"desc": "<p>Mentally add 10 or 100 to a given number 100–900 and mentally subtract 10 or 100 from a given number 100–900.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_NBT_9": {
		"id": "KY_2_NBT_9",
		"ccmathcluster_id": "KY_2_NBT_b",
		"ordinal": "9",
		"desc": "<p>Explain why addition and subtraction strategies work, using place value and the properties of operations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_1": {
		"id": "KY_2_MD_1",
		"ccmathcluster_id": "KY_2_MD_a",
		"ordinal": "1",
		"desc": "<p>Measure the length of an object by selecting and using appropriate tools such as rulers, yardsticks, meter sticks and measuring tapes.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_2": {
		"id": "KY_2_MD_2",
		"ccmathcluster_id": "KY_2_MD_a",
		"ordinal": "2",
		"desc": "<p>Measure the length of an object twice, using length units of different lengths for the two measurements; describe how the two measurements relate to the size of the unit chosen.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_3": {
		"id": "KY_2_MD_3",
		"ccmathcluster_id": "KY_2_MD_a",
		"ordinal": "3",
		"desc": "<p>Estimate lengths using units of inches, feet, yards, centimeters and meters.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_4": {
		"id": "KY_2_MD_4",
		"ccmathcluster_id": "KY_2_MD_a",
		"ordinal": "4",
		"desc": "<p>Measure to determine how much longer one object is than another, expressing the length difference in terms of either a customary or metric standard length unit.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_5": {
		"id": "KY_2_MD_5",
		"ccmathcluster_id": "KY_2_MD_b",
		"ordinal": "5",
		"desc": "<p>Use addition and subtraction within 100 to solve word problems involving lengths that are given in the same units by using drawings and equations with a symbol for the unknown number to represent the problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_6": {
		"id": "KY_2_MD_6",
		"ccmathcluster_id": "KY_2_MD_b",
		"ordinal": "6",
		"desc": "<p>Represent whole numbers as lengths from 0 on a number line with equally spaced points corresponding to the numbers 0, 1, 2, ... and represent whole-number sums and differences within 100 on a number line.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_7": {
		"id": "KY_2_MD_7",
		"ccmathcluster_id": "KY_2_MD_c",
		"ordinal": "7",
		"desc": "<p>Tell and write time from analog and digital clocks to the nearest five minutes, using a.m. and p.m.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_8": {
		"id": "KY_2_MD_8",
		"ccmathcluster_id": "KY_2_MD_c",
		"ordinal": "8",
		"desc": "<p>Solve word problems with adding and subtracting within 100, (not using dollars and cents simultaneously) using the ＄and ￠ symbols appropriately (not including decimal notation). <\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_9": {
		"id": "KY_2_MD_9",
		"ccmathcluster_id": "KY_2_MD_d",
		"ordinal": "9",
		"desc": "<p>Investigate questions involving measurements.<\/p>\r\n<p>a. Identify a statistical question focused on measurements.<\/p>\r\n<p>b. Generate measurement data by measuring lengths of several objects to the nearest whole unit, or by making repeated measurements of the same object.<\/p>\r\n<p>c. Show the measurements by making a dot plot, where the horizontal scale is marked off in whole-number units.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_MD_10": {
		"id": "KY_2_MD_10",
		"ccmathcluster_id": "KY_2_MD_d",
		"ordinal": "10",
		"desc": "<p>Create a pictograph and a bar graph (with single-unit scale) to represent a data set with up to four categories. Solve simple put together, take-apart and compare problems using information presented in a bar graph.<\/p>>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_G_1": {
		"id": "KY_2_G_1",
		"ccmathcluster_id": "KY_2_G_a",
		"ordinal": "1",
		"desc": "<p>Recognize and draw shapes having specified attributes, such as a given number of angles or sides. Identify triangles, quadrilaterals, pentagons, hexagons and cubes (identify number of faces).<\/p>>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_G_2": {
		"id": "KY_2_G_2",
		"ccmathcluster_id": "KY_2_G_a",
		"ordinal": "2",
		"desc": "<p>Partition a rectangle into rows and columns of same-size squares and count to find the total number of them.<\/p>>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_G_3": {
		"id": "KY_2_G_3",
		"ccmathcluster_id": "KY_2_G_a",
		"ordinal": "3",
		"desc": "<p>Partition circles and rectangles into two, three, or four equal shares; describe the shares using the words halves, thirds, half of, a third of, etc.; and describe the whole as two halves, three thirds, four fourths. Recognize that equal shares of identical wholes need not have the same shape.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_2_G_3": {
		"id": "KY_2_G_3",
		"ccmathcluster_id": "KY_2_G_a",
		"ordinal": "3",
		"desc": "<p>Partition circles and rectangles into two, three, or four equal shares; describe the shares using the words halves, thirds, half of, a third of, etc.; and describe the whole as two halves, three thirds, four fourths. Recognize that equal shares of identical wholes need not have the same shape.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	}
}

const domains_3 = {
	"KY_3_OA": {
		"id": "KY_3_OA",
		"grade": "KY.3",
		"ordinal": "OA",
		"name": "Operations and Algebraic Thinking",
		"ordering": "1"
	},
	"KY_3_NBT": {
		"id": "KY_3_NBT",
		"grade": "KY.3",
		"ordinal": "NBT",
		"name": "Number and Operations in Base Ten",
		"ordering": "2"
	},
	"KY_3_NF": {
		"id": "KY_3_NF",
		"grade": "KY.3",
		"ordinal": "NF",
		"name": "Number and Operations Fractions",
		"ordering": "3"
	},
	"KY_3_MD": {
		"id": "KY_3_MD",
		"grade": "KY.3",
		"ordinal": "MD",
		"name": "Measurement and Data",
		"ordering": "4"
	},
	"KY_3_G": {
		"id": "KY_3_G",
		"grade": "KY.3",
		"ordinal": "G",
		"name": "Geometry",
		"ordering": "5"
	}
};

const clusters_3 = {
	"KY_3_OA_a": {
		"id": "KY_3_OA_a",
		"ccmathdomain_id": "KY_3_OA",
		"name": "Represent and solve problems involving multiplication and division.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_OA_b": {
		"id": "KY_3_OA_b",
		"ccmathdomain_id": "KY_3_OA",
		"name": "Understand properties of multiplication and the relationship between multiplication and division.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_OA_c": {
		"id": "KY_3_OA_c",
		"ccmathdomain_id": "KY_3_OA",
		"name": "Multiply and divide within 100.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_OA_d": {
		"id": "KY_3_OA_d",
		"ccmathdomain_id": "KY_3_OA",
		"name": "Solve problems involving the four operations and identify and explain patterns in arithmetic.",
		"ordinal": "4",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_NBT_a": {
		"id": "KY_3_NBT_a",
		"ccmathdomain_id": "KY_3_NBT",
		"name": "Use place value understanding and properties of operations to perform multi-digit arithmetic. Note: A range of algorithms may be used.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_NF_a": {
		"id": "KY_3_NF_a",
		"ccmathdomain_id": "KY_3_NF",
		"name": "Develop understanding of fractions as numbers. Note: grade 3 expectations in this domain are limited to fractions with denominators 2, 3, 4, 6, 8.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_MD_a": {
		"id": "KY_3_MD_a",
		"ccmathdomain_id": "KY_3_MD",
		"name": "Solve problems involving measurement and estimation of intervals of time, liquid volumes and masses of objects.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_MD_b": {
		"id": "KY_3_MD_b",
		"ccmathdomain_id": "KY_3_MD",
		"name": "Understand and apply the statistics process.",
		"ordinal": "2",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_MD_c": {
		"id": "KY_3_MD_c",
		"ccmathdomain_id": "KY_3_MD",
		"name": "Geometric measurement: understand concepts of area and relate area to multiplication and to addition.",
		"ordinal": "3",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_MD_d": {
		"id": "KY_3_MD_d",
		"ccmathdomain_id": "KY_3_MD",
		"name": "Geometric measurement: recognize perimeter as an attribute of plane figures and distinguish between linear and area measures.",
		"ordinal": "4",
		"msa": "0",
		"wap": "0"
	},
	"KY_3_G_a": {
		"id": "KY_3_G_a",
		"ccmathdomain_id": "KY_3_G",
		"name": "Reason with shapes and their attributes.",
		"ordinal": "1",
		"msa": "0",
		"wap": "0"
	}
};

const standards_3 = {
	"KY_3_OA_1": {
		"id": "KY_3_OA_1",
		"ccmathcluster_id": "KY_3_OA_a",
		"ordinal": "1",
		"desc": "<p>Interpret and demonstrate products of whole numbers.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_2": {
		"id": "KY_3_OA_2",
		"ccmathcluster_id": "KY_3_OA_a",
		"ordinal": "2",
		"desc": "<p>Interpret and demonstrate whole-number quotients of whole numbers, where objects are partitioned into equal shares.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_3": {
		"id": "KY_3_OA_3",
		"ccmathcluster_id": "KY_3_OA_a",
		"ordinal": "3",
		"desc": "<p>Use multiplication and division within 100 to solve word problems in situations involving equal groups, arrays and measurement quantities, by using drawings and equations with a symbol for the unknown number to represent the problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_4": {
		"id": "KY_3_OA_4",
		"ccmathcluster_id": "KY_3_OA_a",
		"ordinal": "4",
		"desc": "<p>Determine the unknown whole number in a multiplication or division equation relating three whole numbers.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_5": {
		"id": "KY_3_OA_5",
		"ccmathcluster_id": "KY_3_OA_b",
		"ordinal": "5",
		"desc": "<p>Apply properties of operations as strategies to multiply and divide.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_6": {
		"id": "KY_3_OA_6",
		"ccmathcluster_id": "KY_3_OA_b",
		"ordinal": "6",
		"desc": "<p>Understand division as an unknown-factor problem.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_7": {
		"id": "KY_3_OA_7",
		"ccmathcluster_id": "KY_3_OA_c",
		"ordinal": "7",
		"desc": "<p>Fluently multiply and divide within 100, using strategies such as the relationship between multiplication and division or properties of operations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_8": {
		"id": "KY_3_OA_8",
		"ccmathcluster_id": "KY_3_OA_d",
		"ordinal": "8",
		"desc": "<p>Use various strategies to solve two-step word problems using the four operations (involving only whole numbers with whole number answers). Represent these problems using equations with a letter standing for the unknown quantity. Assess the reasonableness of answers using mental computation and estimation strategies including rounding.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_OA_9": {
		"id": "KY_3_OA_9",
		"ccmathcluster_id": "KY_3_OA_d",
		"ordinal": "9",
		"desc": "<p>Identify arithmetic patterns (including patterns in the addition table or multiplication table) and explain them using properties of operations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_NBT_1": {
		"id": "KY_3_NBT_1",
		"ccmathcluster_id": "KY_3_NBT_a",
		"ordinal": "1",
		"desc": "<p>Use place value understanding to round whole numbers to the nearest 10 or 100.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_NBT_2": {
		"id": "KY_3_NBT_2",
		"ccmathcluster_id": "KY_3_NBT_a",
		"ordinal": "2",
		"desc": "<p>Fluently add and subtract within 1000 using strategies and algorithms based on place value, properties of operations and/or the relationship between addition and subtraction.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_NBT_3": {
		"id": "KY_3_NBT_3",
		"ccmathcluster_id": "KY_3_NBT_a",
		"ordinal": "3",
		"desc": "<p>Multiply one-digit whole numbers by multiples of 10 in the range of 10–90 using strategies based on place value and properties of operations.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_NF_1": {
		"id": "KY_3_NF_1",
		"ccmathcluster_id": "KY_3_NF_a",
		"ordinal": "1",
		"desc": "<p>Understand a fraction 1/𝑏 as the quantity formed by 1 part when a whole is partitioned into b equal parts; understand a fraction 𝑎/𝑏 as the quantity formed by a parts of size 1/𝑏.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_NF_2": {
		"id": "KY_3_NF_2",
		"ccmathcluster_id": "KY_3_NF_a",
		"ordinal": "2",
		"desc": `<p>Understand a fraction as a number on the number line; represent fractions on a number line.<\/p>\r\n
					<p>a. Represent a fraction 1/𝑏 (unit fraction) on a number line by defining the interval from 0 to 1 as the 
					whole and partitioning it into b equal parts.<br>
					• Recognize each part has size 1/𝑏.<br>
					• a unit fraction, 1/𝑏 is located 1/𝑏 of a whole unit from 0 on the number line.<\/p>\r\n
					<p>b. Represent a non-unit fraction 𝑎/𝑏 on a number line by marking off lengths of 1/𝑏 (unit fractions) from 0. 
					Recognize that the resulting interval has size 𝑎/𝑏 and that its endpoint locates the non-unit fraction 𝑎/𝑏 on the number line.
					<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_NF_3": {
		"id": "KY_3_NF_3",
		"ccmathcluster_id": "KY_3_NF_a",
		"ordinal": "3",
		"desc": "<p>Explain equivalence of fractions in special cases and compare fractions by reasoning about their size.<\/p>\r\n<p>a. Understand two fractions as equivalent (equal) if they are the same size, or same point on a number line.<\/p>\r\n<p>b. Recognize and generate simple equivalent fractions. Explain why the fractions are equivalent through writing or drawing.<\/p>\r\n<p>c. Express whole numbers as fractions and recognize fractions that are equivalent to whole numbers.<\/p>\r\n<p>d. Compare two fractions with the same numerator or the same denominator by reasoning about their size. Recognize that comparisons are valid only when the two fractions refer to the same whole. Record the results of comparisons with the symbols >, =, or <, and justify the conclusions.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_1": {
		"id": "KY_3_MD_1",
		"ccmathcluster_id": "KY_3_MD_a",
		"ordinal": "1",
		"desc": "<p>Tell and write time to the nearest minute and measure elapsed time intervals in minutes. Solve word problems involving addition and subtraction of time intervals within and across the hour in minutes.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_2": {
		"id": "KY_3_MD_2",
		"ccmathcluster_id": "KY_3_MD_a",
		"ordinal": "2",
		"desc": "<p>Measure and solve problems involving mass and liquid volume.<\/p>\r\n<p>a. Measure and estimate masses and liquid volumes of objects using standard units of grams (g), kilograms (kg) and liters (L).<\/p>\r\n<p>b. Add, subtract, multiply, or divide to solve one-step word problems involving masses or volumes that are given in the same units.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_3": {
		"id": "KY_3_MD_3",
		"ccmathcluster_id": "KY_3_MD_b",
		"ordinal": "3",
		"desc": "<p>Investigate questions involving categorical data.<\/p>\r\n<p>a. Identify a statistical question focused on categorical data and gather data;<\/p>\r\n<p>b. Create a scaled pictograph and a scaled bar graph to represent a data set (using technology or by hand);<\/p>\r\n<p>c. Make observations from the graph about the question posed, including “how many more” and “how many less” questions.<\/p>\r\n",
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_4": {
		"id": "KY_3_MD_4",
		"ccmathcluster_id": "KY_3_MD_b",
		"ordinal": "4",
		"desc": `<p>Investigate questions involving numerical data.<br>
					a. Identify a statistical question focused on numerical data;<br>
					b. Generate measurement data by measuring lengths using rulers
					marked with halves and fourths of an inch.<br>
					c. Show the data by making a dot plot where the horizontal scale
					is marked off in appropriate units – whole numbers, halves, or
					quarters.<br>
					d. Make observations from the graph about the question posed,
					including questions about the shape of the data and compare
					responses.
					<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_5": {
		"id": "KY_3_MD_5",
		"ccmathcluster_id": "KY_3_MD_c",
		"ordinal": "5",
		"desc": `<p>Recognize area as an attribute of plane figures and
					understand concepts of area measurement.<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_6": {
		"id": "KY_3_MD_6",
		"ccmathcluster_id": "KY_3_MD_c",
		"ordinal": "6",
		"desc": `<p>Measure areas by counting unit squares (square cm, square
					m, square in, square ft. and improvised units).<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_7": {
		"id": "KY_3_MD_7",
		"ccmathcluster_id": "KY_3_MD_c",
		"ordinal": "7",
		"desc": `<p> Relate area to the operations of multiplication and addition.<br>
					a. Find the area of a rectangle with whole-number side lengths by
					tiling it and show the area is the same as would be found by
					multiplying the side lengths.<br>
					b. Multiply side lengths to find areas of rectangles with wholenumber side lengths in the context of solving real world and
					mathematical problems and represent whole-number products
					as rectangular areas in mathematical reasoning.<br>
					c. Use tiling to show in a concrete case the area of a rectangle
					with whole-number side lengths a and b + c is the sum of a × b<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_7": {
		"id": "KY_3_MD_7",
		"ccmathcluster_id": "KY_3_MD_c",
		"ordinal": "7",
		"desc": `<p>Relate area to the operations of multiplication and addition.<br>
					a. Find the area of a rectangle with whole-number side lengths by
					tiling it and show the area is the same as would be found by
					multiplying the side lengths.<br>
					b. Multiply side lengths to find areas of rectangles with wholenumber side lengths in the context of solving real world and
					mathematical problems and represent whole-number products
					as rectangular areas in mathematical reasoning.<br>
					c. Use tiling to show in a concrete case the area of a rectangle
					with whole-number side lengths a and b + c is the sum of a × b
					and a × c. Use area models to represent the distributive
					property in mathematical reasoning.<br>
					d. Recognize area as additive. Find areas of figures that can be
					decomposed into non-overlapping rectangles by adding the
					areas of the non-overlapping parts, applying this technique to
					solve real world problems. <\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_MD_8": {
		"id": "KY_3_MD_8",
		"ccmathcluster_id": "KY_3_MD_d",
		"ordinal": "8",
		"desc": `<p>Solve real world and mathematical problems involving
					perimeters of polygons.<br>
					a. Find the perimeter given the side lengths of a polygon.<br>
					b. Find an unknown side length, given the perimeter and some
					lengths.<br>
					c. Draw rectangles with the same perimeter and different areas
					or with the same area and different perimeters.<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_G_1": {
		"id": "KY_3_G_1",
		"ccmathcluster_id": "KY_3_G_a",
		"ordinal": "1",
		"desc": `<p>Classify polygons by attributes.<br>
					a. Recognize and classify polygons based on the number of sides
					and vertices (triangles, quadrilaterals, pentagons and
					hexagons).<br>
					b. Recognize and classify quadrilaterals (rectangles, squares,
					parallelograms, rhombuses, trapezoids) by side lengths and
					understanding shapes in different categories may share
					attributes and the shared attributes can define a larger
					category.<br>
					c. Identify shapes that do not belong to a given category or
					subcategory.
					<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	},
	"KY_3_G_2": {
		"id": "KY_3_G_2",
		"ccmathcluster_id": "KY_3_G_a",
		"ordinal": "2",
		"desc": `<p>Partition shapes into parts with equal areas. Express the area
						of each part as a unit fraction of the whole.<\/p>\r\n`,
		"example_problem": "",
		"example_problem_url": "",
		"example_problem_attribution": "",
		"progressions": "",
		"links": [],
		"modeling": "0",
		"wap": "1",
		"md": "0",
		"traditional_course_frameworks_a1": "0",
		"traditional_course_frameworks_g": "0",
		"traditional_course_frameworks_a2": "0",
		"integrated_course_frameworks_m1": "0",
		"integrated_course_frameworks_m2": "0",
		"integrated_course_frameworks_m3": "0"
	}
}

const all_domains = {...domains_k, ...domains_1, ...domains_2, ...domains_3 };
const all_clusters = {...clusters_k, ...clusters_1, ...clusters_2, ...clusters_3 };
const all_standards = {...standards_k, ...standards_1, ...standards_2, ...standards_3 };

window.cc = {
	"standards": all_standards,
	"clusters": all_clusters,
	"domains": all_domains,
	"edges": [ ],
	"nd_edges": []
};